---

- name: Install graphite-api dependencies
  apt: pkg={{item}} update_cache=yes cache_valid_time=60
  with_items:
  - libcairo2
  - libcairo-dev
  - libffi5
  - libffi-dev
  - libyaml-dev

- name: Create graphite-api user
  user: name={{graphite_api_user}} home={{graphite_api_dir}}

- name: Setup virtualenv for graphite-api
  shell: virtualenv {{graphite_api_dir}}/env --python=python creates={{graphite_api_dir}}/env/bin/pip
  sudo: yes
  sudo_user: "{{graphite_api_user}}"

- name: Install graphite-api
  pip: name={{item}} executable={{graphite_api_dir}}/env/bin/pip
  sudo: yes
  sudo_user: "{{graphite_api_user}}"
  with_items:
  - flask
  - flask-cache
  - https://github.com/Dieterbe/graphite-api/tarball/support-templates2
#  - graphite-api use instead patched version ^

- name: Configure graphite-api
  template: src=config.yml.j2 dest={{graphite_api_dir}}/config.yml owner={{graphite_api_user}} group={{graphite_api_group}}

- include: whisper.yml
  tags: [graphite-api, graphite-api-whisper]
  when: graphite_api_whisper

- include: influxdb.yml
  tags: [graphite-api, graphite-api-influxdb]
  when: influxdb_enabled and graphite_api_influxdb

- include: nginx.yml
  tags: [graphite-api, graphite-api-nginx]
  when: nginx_enabled and graphite_api_nginx

- include: uwsgi.yml
  tags: [graphite-api, graphite-api-uwsgi]
  when: uwsgi_enabled and graphite_api_uwsgi
