---

- name: Configure nginx graphite-api site
  template: src=nginx-graphite-api.conf.j2 dest={{nginx_sites_available}}/graphite-api.conf
  notify: [nginx reload]

- name: Enable nginx graphite-api site
  file: src={{nginx_sites_available}}/graphite-api.conf dest={{nginx_sites_enabled}}/graphite-api.conf state=link
  notify: [nginx reload]
