---

- name: Install nignx
  apt: pkg=nginx default_release=wheezy-backports update_cache=yes cache_valid_time=60

- name: Configure nginx
  template: src=nginx.conf.j2 dest={{nginx_dir}}/nginx.conf
  notify:
    - nginx reload
